name: Node.js CI/CD

on:
  push:
    branches: [ main, staging, production ]
  pull_request:
    branches: [ main, staging, production ]

# Environment variables are defined within each job that needs them

jobs:
  build:
    name: Build with Node.js 24.x
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 24.x
      uses: actions/setup-node@v3
      with:
        node-version: 24.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Copy GOV.UK assets
      run: npm run copy-govuk-assets
    - name: Build application
      run: npm run build --if-present
    - name: Run minimal tests
      run: npm run test:minimal

  deploy-staging:
    name: Deploy to Staging
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Copy GOV.UK assets
        run: npm run copy-govuk-assets
      - name: Deploy to Heroku Staging
        uses: akhileshns/heroku-deploy@v3.12.14
        env:
          HD_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HD_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        with:
          heroku_api_key: ${{ env.HD_API_KEY }}
          heroku_app_name: "rrdm-stage"
          heroku_email: ${{ env.HD_EMAIL }}
          usedocker: true

  deploy-production:
    name: Deploy to Production
    needs: build
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Copy GOV.UK assets
        run: npm run copy-govuk-assets
      - name: Deploy to Heroku Production
        uses: akhileshns/heroku-deploy@v3.12.14
        env:
          HD_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HD_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        with:
          heroku_api_key: ${{ env.HD_API_KEY }}
          heroku_app_name: "rrdm-production"
          heroku_email: ${{ env.HD_EMAIL }}
          usedocker: true
