name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-versions:
    name: Verify Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 24.1.0
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'
      - name: Install npm 11.3.0
        run: |
          npm install -g npm@11.3.0
          node -v
          npm -v

  install-dependencies:
    name: Install Dependencies
    needs: verify-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'
      - name: Install npm 11.3.0
        run: npm install -g npm@11.3.0
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build:
    name: Build Application
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'
      - name: Install npm 11.3.0
        run: npm install -g npm@11.3.0
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Copy GOV.UK assets
        run: npm run copy-govuk-assets
      - name: Build application
        run: npm run build --if-present

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'
      - name: Install npm 11.3.0
        run: npm install -g npm@11.3.0
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: |
          echo "Running tests with NODE_ENV=test"
          NODE_ENV=test npm run test:minimal -- --verbose
      - name: Run linting
        run: npm run lint

