name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 24.x
      uses: actions/setup-node@v3
      with:
        node-version: 24.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Copy GOV.UK assets
      run: npm run copy-govuk-assets
    - name: Build application
      run: npm run build --if-present
    - name: Debug Node.js and npm versions
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        echo "Jest version: $(npm list jest --depth=0 | grep jest)"
        echo "Package.json test scripts:"
        grep -A 5 "test:" package.json
    - name: Run minimal tests with debug info
      run: |
        echo "Running tests with NODE_ENV=test"
        NODE_ENV=test npm run test:minimal -- --verbose
