name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NODE_OPTIONS: --max-old-space-size=4096
    
    strategy:
      matrix:
        node-version: ['24.1.0']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install npm 11.3.0
      run: npm install -g npm@11.3.0
    
    - name: Verify versions
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
    
    - name: Copy GOV.UK assets
      run: npm run copy-govuk-assets
    
    - name: Run tests
      run: |
        npm run test:minimal -- --verbose --detectOpenHandles --forceExit
    
    - name: Run linting
      run: npm run lint
      continue-on-error: true
